---
title: "ovejas"
format: html
editor: visual
---

## 

```{r, warning =FALSE, message=FALSE}
library(readxl)
library(tidyverse)
library(ggplot2)
library(rcartocolor)
```

Cargamos datos

```{r}

datos <- read_excel("datosovejas.xlsx", sheet = "Datos hasta señalada", na = "." )
str(datos)

datos$Tiponac[datos$Tiponac == "3"] <- 2 #recodificacion

datos_preparto <- datos |> filter( Momento == "Preparto") #momento elegido para el primer analisis

```

Analisis de datos faltantes

```{r}
nrow(na.omit(datos_preparto)) #159 174 yipii 

nrow(na.omit(datos))

nrow(na.omit(datos |> filter( Momento == "Preencarnerada") )) #57

datos_preparto <- na.omit(datos_preparto)
```

Recodificacion de las variables

```{r, warning =FALSE}

datos_preparto <- datos_preparto |> 
  mutate(Edad = as.factor(Edad),
         Partos = as.factor(Partos),
         Pesove = as.numeric(Pesove),
         CCove = as.numeric(CCove),
         LOTE = as.factor(LOTE),
         Tiponac = as.factor(Tiponac),
         Potrepari = as.factor(Potrepari),
         Sex = as.factor(Sex),
         Gainseñal = as.numeric(Gainseñal),
         Nodu = as.factor(Nodu),
         Induru = as.factor(Induru),
         Nodpez = as.factor(Nodpez),
         Indupez = as.factor(Indupez),
         Eco = as.factor(Eco),
         Ancubre = as.numeric(Ancubre),
         Peznum = as.factor(Peznum),
         Suspen = as.factor(Suspen),
         Separ = as.factor(Separ),
         Ubicpez = as.factor(Ubicpez),
         Simet = as.factor(Simet) ) 

str(datos_preparto)

#Detectamos que no hay nodulos en los pezones
which(datos_preparto$Indupez == 1) #hay uno solo
datos_preparto$Indupez[datos_preparto$Indupez == 1] 

datos_preparto <- datos_preparto |> select(-PadCord, -PN, -Nodpez, -Indupez)


#nrow(datos_preparto |> filter(if_any(everything(), ~ !is.na(.x))) )
```

```{r}
datos_preparto <- datos_preparto |> 
  mutate(
    Partos = fct_recode(Partos,"Multipara" = "M","Primipara" = "P"),
    LOTE = fct_recode(LOTE,"Inseminación artificial" = "IA",
                           "Repaso con carnero" = "R"),
    Tiponac = fct_recode(Tiponac, "Simple" = "1","Múltiple" = "2"),
    Sex = fct_recode(Sex,"Hembra" = "H","Macho" = "M"),
    Nodu = fct_recode(Nodu, "Ausencia" = "0","Presencia" = "1"),
    Induru = fct_recode(Induru,"Ausencia" = "0","Presencia" = "1"),
    Eco = fct_recode(Eco,"Normal" = "0","Alteración" = "1"),
    Peznum = fct_recode(Peznum, "Ausencia" = "0","Presencia" = "1"),
    Suspen = fct_recode(Suspen,"Ancha" = "1",
                               "Cuadrada" = "2",
                               "Pendulada" = "3"),
    Separ = fct_recode(Separ,"Marcada" = "1",
                             "Moderada" = "2",
                             "Sin" = "3"),
    Ubicpez = fct_recode(Ubicpez, "Lateral" = "1",
                                  "Vertical" = "2",
                                  "Horizontal" = "3"),
    Simet = fct_recode(Simet, "Simétrica" = "0", "No simétrica" = "1")
  )
```

```{r}
#Para graficar variables categoricas
cat_vars <- names(Filter(is.factor, datos_preparto))

nombresbien <- c("Edad (cronología dentaria)", 
                 "Número de partos",
                 "Manejo reproductivo",
                 "Tipo de nacimiento",
                 "Potrero",
                 "Sexo",
                 "Nodulos en ubre",
                 "Induración en ubre",
                 "Alteraciones ecograficas",
                 "Pezones supernumerarios",
                 "Suspensión ubre",
                 "Separación ubre",
                 "Ubicación pezones",
                 "Simetría ubre"    )
```

```{r}
#CORRELACION ENTRE PESOOVEJA, CCOVE, medidas, CON GAINSENAL

num_vars <- datos_preparto |> 
  select(where(is.numeric)) |> 
  names()

num_vars <- setdiff(num_vars, c("IDM", "Idcord", "Gainseñal"))

nombres_num <- c("Peso de la oveja",
                 "Condición corporal de la oveja",
                 "Largo de ubre (cm)",
                 "Ancho de ubre (cm)",
                 "Ancho del pezón (cm)",
                 "Largo del pezón (cm)")

for (i in 1:length(num_vars)) {
  
  graficos <- ggplot(datos_preparto, 
                     aes(x= .data[[num_vars[i]]], 
                         y= Gainseñal)) +
    
    geom_point(color = "purple3") +
    theme_minimal() +
    xlab(nombres_num[i]) +
    ylab("Ganancia media de peso diario")
  
  print(graficos)
  
}
  
 
```

```{r}
#Variables categóricas

#NODULOS CHEQUEAR CUANTAS TIENEN
#INDURACIONES IDEM. AUNQUE HAY UN POCO MAS
#pocas no simet

for (i in 1:length(cat_vars)) {
  graficos <- ggplot(datos_preparto, aes(x= .data[[cat_vars[i]]], 
                                        fill = .data[[cat_vars[i]]])) + 
    geom_bar() +
    theme_minimal() +
    xlab(nombresbien[i]) +
    theme(legend.position = "none") +
    scale_fill_carto_d(palette = "SunsetDark", 
                       type = "qualitative",
                       name = nombresbien[i])
  
  print(graficos)
} 
```

**#OJO DATOS NO HOMOGENEOS PREGUNTAR EL PARTES // SE PUEDEN PONDERAR O PENALIZAR LAS CATEGORIAS PARA BALANCEAR LOS DATOS**

Relacion entre variables categoricas y la respuesta

```{r}

for(i in 1:length(cat_vars)) {
   
  g <- ggplot(datos_preparto, aes(x = .data[[cat_vars[i]]], 
                             y = Gainseñal,
                             fill = .data[[cat_vars[i]]] )) + 
    geom_boxplot() +
    ylab('Ganancia media de peso diario') +
    xlab(nombresbien[i]) +
    scale_fill_carto_d(palette = "SunsetDark", 
                       type = "qualitative",
                       name = nombresbien[i]) +
    theme_minimal() +
    theme(legend.position = "none",
          axis.title.x = element_text(margin = margin(t = 20)),
          axis.title.y = element_text(margin = margin(t = 20))) 
  
  print(g)
}




```

VER INTERACCIONES

#POTRERO Y TIPONAC INTERACCION!!!

#EDAD Y CONDICION CORPORAL
